// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWyMX0kn6z684SMWBgCq1N5VwSWhT4hMg',
    appId: '1:643458128532:web:969df84c1f206da6edf281',
    messagingSenderId: '643458128532',
    projectId: 'bingo-4a1cc',
    authDomain: 'bingo-4a1cc.firebaseapp.com',
    storageBucket: 'bingo-4a1cc.appspot.com',
    measurementId: 'G-EK78W7N473',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkM_DrQ68WgaM-oVB3zNWDIRPOuQRt_7g',
    appId: '1:643458128532:android:6fc9d395695634d2edf281',
    messagingSenderId: '643458128532',
    projectId: 'bingo-4a1cc',
    storageBucket: 'bingo-4a1cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc92X8tyhuE_krw2xah4XxDjZ6irfoJPc',
    appId: '1:643458128532:ios:410181a01b4be613edf281',
    messagingSenderId: '643458128532',
    projectId: 'bingo-4a1cc',
    storageBucket: 'bingo-4a1cc.appspot.com',
    iosBundleId: 'uz.cli.bingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc92X8tyhuE_krw2xah4XxDjZ6irfoJPc',
    appId: '1:643458128532:ios:379032b396cd7265edf281',
    messagingSenderId: '643458128532',
    projectId: 'bingo-4a1cc',
    storageBucket: 'bingo-4a1cc.appspot.com',
    iosBundleId: 'com.example.bingo.RunnerTests',
  );
}
